module CWE

    ID16 = {title:  'CWE CATEGORY: Configuration', 'link': 'https://cwe.mitre.org/data/definitions/16.html'}
    ID19 = {title:  'CWE CATEGORY: Data Processing Errors', 'link': 'https://cwe.mitre.org/data/definitions/19.html'}
    ID20 = {title:  'CWE-20: Improper Input Validation', 'link': 'https://cwe.mitre.org/data/definitions/20.html'}
    ID22 = {title:  'CWE-22: Improper Limitation of a Pathname to a Restricted Directory (\'Path Traversal\')', 'link': 'https://cwe.mitre.org/data/definitions/22.html'}
    ID73 = {title:  'CWE-73: External Control of File Name or Path', 'link': 'https://cwe.mitre.org/data/definitions/73.html'}
    ID78 = {title:  'CWE-78: Improper Neutralization of Special Elements used in an OS Command (\'OS Command Injection\')', 'link': 'https://cwe.mitre.org/data/definitions/78.html'}
    ID79 = {title:  'CWE-79: Improper Neutralization of Input During Web Page Generation (\'Cross-site Scripting\')', 'link': 'https://cwe.mitre.org/data/definitions/79.html'}
    ID89 = {title:  'CWE-89: Improper Neutralization of Special Elements used in an SQL Command (\'SQL Injection\')', 'link': 'https://cwe.mitre.org/data/definitions/89.html'}
    ID94 = {title:  'CWE-94: Improper Control of Generation of Code (\'Code Injection\')', 'link': 'https://cwe.mitre.org/data/definitions/94.html'}
    ID95 = {title:  'CWE-95: Improper Neutralization of Directives in Dynamically Evaluated Code (\'Eval Injection\')', 'link': 'https://cwe.mitre.org/data/definitions/95.html'}
    ID98 = {title:  'CWE-98: Improper Control of Filename for Include/Require Statement in PHP Program (\'PHP Remote File Inclusion\')', 'link': 'https://cwe.mitre.org/data/definitions/98.html'}
    ID116 = {title: 'CWE-116: Improper Encoding or Escaping of Output', 'link': 'https://cwe.mitre.org/data/definitions/116.html'}
    ID117 = {title: 'CWE-117: Improper Output Neutralization for Logs', 'link': 'https://cwe.mitre.org/data/definitions/117.html'}
    ID120 = {title: 'CWE-120: Buffer Copy without Checking Size of Input (\'Classic Buffer Overflow\')', 'link': 'https://cwe.mitre.org/data/definitions/120.html'}
    ID134 = {title: 'CWE-134: Use of Externally-Controlled Format String', 'link': 'https://cwe.mitre.org/data/definitions/134.html'}
    ID138 = {title: 'CWE-138: Improper Neutralization of Special Elements', 'link': 'https://cwe.mitre.org/data/definitions/138.html'}
    ID147 = {title: 'CWE-147: Improper Neutralization of Input Terminators', 'link': 'https://cwe.mitre.org/data/definitions/147.html'}
    ID159 = {title: 'CWE-159: Failure to Sanitize Special Element', 'link': 'https://cwe.mitre.org/data/definitions/159.html'}
    ID173 = {title: 'CWE-173: Improper Handling of Alternate Encoding', 'link': 'https://cwe.mitre.org/data/definitions/173.html'}
    ID176 = {title: 'CWE-176: Improper Handling of Unicode Encoding', 'link': 'https://cwe.mitre.org/data/definitions/176.html'}
    ID190 = {title: 'CWE-190: Integer Overflow or Wraparound', 'link': 'https://cwe.mitre.org/data/definitions/190.html'}
    ID200 = {title: 'CWE-200: Information Exposure', 'link': 'https://cwe.mitre.org/data/definitions/200.html'}
    ID209 = {title: 'CWE-209: Information Exposure Through an Error Message', 'link': 'https://cwe.mitre.org/data/definitions/209.html'}
    ID210 = {title: 'CWE-210: Information Exposure Through Self-generated Error Message', 'link': 'https://cwe.mitre.org/data/definitions/210.html'}
    ID212 = {title: 'CWE-212: Improper Cross-boundary Removal of Sensitive Data', 'link': 'https://cwe.mitre.org/data/definitions/212.html'}
    ID226 = {title: 'CWE-226: Sensitive Information Uncleared Before Release', 'link': 'https://cwe.mitre.org/data/definitions/226.html'}
    ID233 = {title: 'CWE-233: Improper Handling of Parameters', 'link': 'https://cwe.mitre.org/data/definitions/233.html'}
    ID235 = {title: 'CWE-235: Improper Handling of Extra Parameters', 'link': 'https://cwe.mitre.org/data/definitions/235.html'}
    ID250 = {title: 'CWE-250: Execution with Unnecessary Privileges', 'link': 'httpsCWE-250: Execution with Unnecessary Privileges://cwe.mitre.org/data/definitions/250.html'}
    ID255 = {title: 'CWE CATEGORY: Credentials Management', 'link': 'https://cwe.mitre.org/data/definitions/255.html'}
    ID256 = {title: 'CWE-256: Unprotected Storage of Credentials', 'link': 'https://cwe.mitre.org/data/definitions/256.html'}
    ID263 = {title: 'CWE-263: Password Aging with Long Expiration', 'link': 'https://cwe.mitre.org/data/definitions/263.html'}
    ID265 = {title: 'CWE CATEGORY: Privilege / Sandbox Issues', 'link': 'https://cwe.mitre.org/data/definitions/265.html'}
    ID272 = {title: 'CWE-272: Least Privilege Violation', 'link': 'https://cwe.mitre.org/data/definitions/272.html'}
    ID275 = {title: 'CWE CATEGORY: Permission Issues', 'link': 'https://cwe.mitre.org/data/definitions/275.html'}
    ID276 = {title: 'CWE-276: Incorrect Default Permissions', 'link': 'https://cwe.mitre.org/data/definitions/276.html'}
    ID284 = {title: 'CWE-284: Improper Access Control', 'link': 'https://cwe.mitre.org/data/definitions/284.html'}
    ID285 = {title: 'CWE-285: Improper Authorization', 'link': 'https://cwe.mitre.org/data/definitions/285.html'}
    ID287 = {title: 'CWE-287: Improper Authentication', 'link': 'https://cwe.mitre.org/data/definitions/287.html'}
    ID290 = {title: 'CWE-290: Authentication Bypass by Spoofing', 'link': 'https://cwe.mitre.org/data/definitions/290.html'}
    ID295 = {title: 'CWE-295: Improper Certificate ValidationCWE-299: Improper Check for Certificate Revocation', 'link': 'https://cwe.mitre.org/data/definitions/295.html'}
    ID299 = {title: 'CWE-299: Improper Check for Certificate Revocation', 'link': 'https://cwe.mitre.org/data/definitions/299.html'}
    ID304 = {title: 'CWE-304: Missing Critical Step in Authentication', 'link': 'https://cwe.mitre.org/data/definitions/304.html'}
    ID306 = {title: 'CWE-306: Missing Authentication for Critical Function', 'link': 'https://cwe.mitre.org/data/definitions/306.html'}
    ID307 = {title: 'CWE-307: Improper Restriction of Excessive Authentication Attempts', 'link': 'https://cwe.mitre.org/data/definitions/307.html'}
    ID308 = {title: 'CWE-308: Use of Single-factor Authentication', 'link': 'https://cwe.mitre.org/data/definitions/308.html'}
    ID310 = {title: 'CWE CATEGORY: Cryptographic Issues', 'link': 'https://cwe.mitre.org/data/definitions/310.html'}
    ID311 = {title: 'CWE-311: Missing Encryption of Sensitive Data', 'link': 'https://cwe.mitre.org/data/definitions/311.html'}
    ID319 = {title: 'CWE-319: Cleartext Transmission of Sensitive Information', 'link': 'https://cwe.mitre.org/data/definitions/319.html'}
    ID320 = {title: 'CWE CATEGORY: Key Management Errors', 'link': 'https://cwe.mitre.org/data/definitions/320.html'}
    ID326 = {title: 'CWE-326: Inadequate Encryption Strength', 'link': 'https://cwe.mitre.org/data/definitions/326.html'}
    ID327 = {title: 'CWE-327: Use of a Broken or Risky Cryptographic Algorithm', 'link': 'https://cwe.mitre.org/data/definitions/327.html'}
    ID330 = {title: 'CWE-330: Use of Insufficiently Random Values', 'link': 'https://cwe.mitre.org/data/definitions/330.html'}
    ID331 = {title: 'CWE-331: Insufficient Entropy', 'link': 'https://cwe.mitre.org/data/definitions/331.html'}
    ID338 = {title: 'CWE-338: Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)', 'link': 'https://cwe.mitre.org/data/definitions/338.html'}
    ID345 = {title: 'CWE-345: Insufficient Verification of Data Authenticity', 'link': 'https://cwe.mitre.org/data/definitions/345.html'}
    ID346 = {title: 'CWE-346: Origin Validation Error', 'link': 'https://cwe.mitre.org/data/definitions/346.html'}
    ID350 = {title: 'CWE-350: Reliance on Reverse DNS Resolution for a Security-Critical Action', 'link': 'https://cwe.mitre.org/data/definitions/350.html'}
    ID352 = {title: 'CWE-352: Cross-Site Request Forgery (CSRF)', 'link': 'https://cwe.mitre.org/data/definitions/352.html'}
    ID353 = {title: 'CWE-353: Missing Support for Integrity Check', 'link': 'https://cwe.mitre.org/data/definitions/353.html'}
    ID359 = {title: 'CWE-359: Exposure of Private Information (\'Privacy Violation\')', 'link': 'https://cwe.mitre.org/data/definitions/359.html'}
    ID362 = {title: 'CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization (\'Race Condition\')', 'link': 'https://cwe.mitre.org/data/definitions/362.html'}
    ID367 = {title: 'CWE-367: Time-of-check Time-of-use (TOCTOU) Race Condition', 'link': 'https://cwe.mitre.org/data/definitions/367.html'}
    ID384 = {title: 'CWE-384: Session Fixation', 'link': 'https://cwe.mitre.org/data/definitions/384.html'}
    ID385 = {title: 'CWE-385: Covert Timing Channel', 'link': 'https://cwe.mitre.org/data/definitions/385.html'}
    ID390 = {title: 'CWE-390: Detection of Error Condition Without Action', 'link': 'https://cwe.mitre.org/data/definitions/390.html'}
    ID400 = {title: 'CWE-400: Uncontrolled Resource Consumption', 'link': 'https://cwe.mitre.org/data/definitions/400.html'}
    ID409 = {title: 'CWE-409: Improper Handling of Highly Compressed Data (Data Amplification)', 'link': 'https://cwe.mitre.org/data/definitions/409.html'}
    ID419 = {title: 'CWE-419: Unprotected Primary Channel', 'link': 'https://cwe.mitre.org/data/definitions/419.html'}
    ID434 = {title: 'CWE-434: Unrestricted Upload of File with Dangerous Type', 'link': 'https://cwe.mitre.org/data/definitions/434.html'}
    ID436 = {title: 'CWE-436: Interpretation Conflict', 'link': 'https://cwe.mitre.org/data/definitions/436.html'}
    ID460 = {title: 'CWE-460: Improper Cleanup on Thrown Exception', 'link': 'https://cwe.mitre.org/data/definitions/460.html'}
    ID477 = {title: 'CWE-477: Use of Obsolete Function', 'link': 'https://cwe.mitre.org/data/definitions/477.html'}
    ID494 = {title: 'CWE-494: Download of Code Without Integrity Check', 'link': 'https://cwe.mitre.org/data/definitions/494.html'}
    ID497 = {title: 'CWE-497: Exposure of System Data to an Unauthorized Control Sphere', 'link': 'https://cwe.mitre.org/data/definitions/497.html'}
    ID502 = {title: 'CWE-502: Deserialization of Untrusted Data', 'link': 'https://cwe.mitre.org/data/definitions/502.html'}
    ID507 = {title: 'CWE-507: Trojan Horse', 'link': 'https://cwe.mitre.org/data/definitions/507.html'}
    ID509 = {title: 'CWE-509: Replicating Malicious Code (Virus or Worm)', 'link': 'https://cwe.mitre.org/data/definitions/509.html'}
    ID511 = {title: 'CWE-511: Logic/Time Bomb', 'link': 'https://cwe.mitre.org/data/definitions/511.html'}
    ID521 = {title: 'CWE-521: Weak Password Requirements', 'link': 'https://cwe.mitre.org/data/definitions/521.html'}
    ID522 = {title: 'CWE-522: Insufficiently Protected Credentials', 'link': 'https://cwe.mitre.org/data/definitions/522.html'}
    ID523 = {title: 'CWE-523: Unprotected Transport of Credentials', 'link': 'https://cwe.mitre.org/data/definitions/523.html'}
    ID524 = {title: 'CWE-524: Information Exposure Through Caching', 'link': 'https://cwe.mitre.org/data/definitions/524.html'}
    ID525 = {title: 'CWE-525: Information Exposure Through Browser Caching', 'link': 'https://cwe.mitre.org/data/definitions/525.html'}
    ID532 = {title: 'CWE-532: Inclusion of Sensitive Information in Log Files', 'link': 'https://cwe.mitre.org/data/definitions/532.html'}
    ID539 = {title: 'CWE-539: Information Exposure Through Persistent Cookies', 'link': 'https://cwe.mitre.org/data/definitions/539.html'}
    ID544 = {title: 'CWE-544: Missing Standardized Error Handling Mechanism', 'link': 'https://cwe.mitre.org/data/definitions/544.html'}
    ID548 = {title: 'CWE-548: Information Exposure Through Directory Listing', 'link': 'https://cwe.mitre.org/data/definitions/548.html'}
    ID552 = {title: 'CWE-552: Files or Directories Accessible to External Parties', 'link': 'https://cwe.mitre.org/data/definitions/552.html'}
    ID598 = {title: 'CWE-598: Information Exposure Through Query Strings in GET Request', 'link': 'https://cwe.mitre.org/data/definitions/598.html'}
    ID601 = {title: 'CWE-601: URL Redirection to Untrusted Site (\'Open Redirect\')', 'link': 'https://cwe.mitre.org/data/definitions/601.html'}
    ID602 = {title: 'CWE-602: Client-Side Enforcement of Server-Side Security', 'link': 'https://cwe.mitre.org/data/definitions/602.html'}
    ID611 = {title: 'CWE-611: Improper Restriction of XML External Entity Reference', 'link': 'https://cwe.mitre.org/data/definitions/611.html'}
    ID613 = {title: 'CWE-613: Insufficient Session Expiration', 'link': 'https://cwe.mitre.org/data/definitions/613.html'}
    ID614 = {title: 'CWE-614: Sensitive Cookie in HTTPS Session Without \'Secure\' Attribute', 'link': 'https://cwe.mitre.org/data/definitions/614.html'}
    ID620 = {title: 'CWE-620: Unverified Password Change', 'link': 'https://cwe.mitre.org/data/definitions/620.html'}
    ID637 = {title: 'CWE-637: Unnecessary Complexity in Protection Mechanism (Not Using \'Economy of Mechanism\')', 'link': 'https://cwe.mitre.org/data/definitions/637.html'}
    ID639 = {title: 'CWE-639: Authorization Bypass Through User-Controlled Key', 'link': 'https://cwe.mitre.org/data/definitions/639.html'}
    ID640 = {title: 'CWE-640: Weak Password Recovery Mechanism for Forgotten Password', 'link': 'https://cwe.mitre.org/data/definitions/640.html'}
    ID641 = {title: 'CWE-641: Improper Restriction of Names for Files and Other Resources', 'link': 'https://cwe.mitre.org/data/definitions/641.html'}
    ID643 = {title: 'CWE-643: Improper Neutralization of Data within XPath Expressions (\'XPath Injection\')', 'link': 'https://cwe.mitre.org/data/definitions/643.html'}
    ID646 = {title: 'CWE-646: Reliance on File Name or Extension of Externally-Supplied File', 'link': 'https://cwe.mitre.org/data/definitions/646.html'}
    ID650 = {title: 'CWE-650: Trusting HTTP Permission Methods on the Server Side', 'link': 'https://cwe.mitre.org/data/definitions/650.html'}
    ID714 = {title: 'CWE CATEGORY: OWASP Top Ten 2007 Category A3 - Malicious File Execution', 'link': 'https://cwe.mitre.org/data/definitions/714.html'}
    ID732 = {title: 'CWE-732: Incorrect Permission Assignment for Critical Resource', 'link': 'https://cwe.mitre.org/data/definitions/732.html'}
    ID749 = {title: 'CWE-749: Exposed Dangerous Method or Function', 'link': 'https://cwe.mitre.org/data/definitions/749.html'}
    ID754 = {title: 'CWE-754: Improper Check for Unusual or Exceptional Conditions', 'link': 'https://cwe.mitre.org/data/definitions/754.html'}
    ID770 = {title: 'CWE-770: Allocation of Resources Without Limits or Throttling', 'link': 'https://cwe.mitre.org/data/definitions/770.html'}
    ID778 = {title: 'CWE-778: Insufficient Logging', 'link': 'https://cwe.mitre.org/data/definitions/778.html'}
    ID779 = {title: 'CWE-779: Logging of Excessive Data', 'link': 'https://cwe.mitre.org/data/definitions/779.html'}
    ID798 = {title: 'CWE-798: Use of Hard-coded Credentials', 'link': 'https://cwe.mitre.org/data/definitions/798.html'}
    ID829 = {title: 'CWE-829: Inclusion of Functionality from Untrusted Control Sphere', 'link': 'https://cwe.mitre.org/data/definitions/829.html'}
    ID830 = {title: 'CWE-830: Inclusion of Web Functionality from an Untrusted Source', 'link': 'https://cwe.mitre.org/data/definitions/830.html'}
    ID841 = {title: 'CWE-841: Improper Enforcement of Behavioral Workflow', 'link': 'https://cwe.mitre.org/data/definitions/841.html'}
    ID915 = {title: 'CWE-915: Improperly Controlled Modification of Dynamically-Determined Object Attributes', 'link': 'https://cwe.mitre.org/data/definitions/915.html'}
    ID916 = {title: 'CWE-916: Use of Password Hash With Insufficient Computational Effort', 'link': 'https://cwe.mitre.org/data/definitions/916.html'}
    ID918 = {title: 'CWE-918: Server-Side Request Forgery (SSRF)', 'link': 'https://cwe.mitre.org/data/definitions/918.html'}
    ID922 = {title: 'CWE-922: Insecure Storage of Sensitive Information', 'link': 'https://cwe.mitre.org/data/definitions/922.html'}
    ID923 = {title: 'CWE-923: Improper Restriction of Communication Channel to Intended Endpoints', 'link': 'https://cwe.mitre.org/data/definitions/923.html'}
    ID943 = {title: 'CWE-943: Improper Neutralization of Special Elements in Data Query Logic', 'link': 'https://cwe.mitre.org/data/definitions/943.html'}
    ID1002 = {title: 'CWE CATEGORY: SFP Secondary Cluster: Unexpected Entry Points', 'link': 'https://cwe.mitre.org/data/definitions/1002.html'}
    ID1004 = {title: 'CWE-1004: Sensitive Cookie Without \'HttpOnly\' Flag', 'link': 'https://cwe.mitre.org/data/definitions/1004.html'}
    ID1009 = {title: 'CWE CATEGORY: Audit', 'link': 'https://cwe.mitre.org/data/definitions/1009.html'}
    ID1021 = {title: 'CWE-1021: Improper Restriction of Rendered UI Layers or Frames', 'link': 'https://cwe.mitre.org/data/definitions/1021.html'}
    ID1026 = {title: 'CWE VIEW: Weaknesses in OWASP Top Ten (2017)', 'link': 'https://cwe.mitre.org/data/definitions/1026.html'}
    ID1029 = {title: 'CWE CATEGORY: OWASP Top Ten 2017 Category A3 - Sensitive Data Exposure', 'link': 'https://cwe.mitre.org/data/definitions/1029.html'}
    ID1053 = {title: 'CWE-1053: Missing Documentation for Design', 'link': 'https://cwe.mitre.org/data/definitions/1053.html'}
    ID1059 = {title: 'CWE-1059: Incomplete Documentation', 'link': 'https://cwe.mitre.org/data/definitions/1059.html'}
    ID1104 = {title: 'CWE-1104: Use of Unmaintained Third Party Components', 'link': 'https://cwe.mitre.org/data/definitions/1104.html'}
    ID1110 = {title: 'CWE-1110: Incomplete Design Documentation', 'link': 'https://cwe.mitre.org/data/definitions/1110.html'}
end